version: 0.0
os: linux
files:
  - source: daikokuten
   destination: /etc/init.d/
  - source: /src
   destination: /home/ec2-user/daikokuten
  - source: requirements.txt
   destination: /home/ec2-user/daikokuten
permissions:
  - object: /etc/init.d/
    pattern: "daikokuten"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root